import logging
import pathlib

import jax.numpy as jnp
import numpy as np

from smefit.rge import RGE, load_precomputed_rge_matrix, load_rge_mats_from_scales

current_file_path = pathlib.Path(__file__).resolve().parent

oo_ww_wc_basis = ["OpD", "OpWB", "OWWW", "Opl1", "Ope", "O3pl1"]
oo_tt_wc_basis = ["OpQM", "Opt", "OtW", "OtZ", "OQl1M", "OQe", "Otl1", "Ote"]

_logger = logging.getLogger(__name__)


def compute_rge_matrix(coefficients, rge_dict, scale):
    coeff_list = list(coefficients.names)
    init_scale = float(rge_dict["init_scale"])
    smeft_accuracy = str(rge_dict.get("smeft_accuracy", "integrate"))
    adm_QCD = bool(rge_dict.get("adm_QCD", False))
    yukawa = str(rge_dict.get("yukawa", "top"))
    rge_settings = {
        "init_scale": init_scale,
        "smeft_accuracy": smeft_accuracy,
        "adm_QCD": adm_QCD,
        "yukawa": yukawa,
    }

    rge_cache = {}
    path_to_rge_mat = rge_dict.get("rg_matrix", False)
    if path_to_rge_mat:
        rge_cache = load_precomputed_rge_matrix(path_to_rge_mat, rge_settings)

    rge_runner = RGE(
        wc_names=coeff_list,
        init_scale=init_scale,
        accuracy=smeft_accuracy,
        adm_QCD=adm_QCD,
        yukawa=yukawa,
    )
    rge_df = load_rge_mats_from_scales([scale], coeff_list, rge_runner, rge_cache)[0]
    gen_operators = list(rge_df.index)
    _logger.info("The operators generated by the RGE are: %s", gen_operators)

    return rge_df.values, np.array(gen_operators)


class DescopedOptimalWWFCCee161:
    def __init__(self, coefficients, rge_dict=None, lumi_scale=1.0):
        if rge_dict is not None:
            _obs_scale = rge_dict.get("obs_scale", "dynamic")
            rgemat, coeff_names = compute_rge_matrix(
                coefficients,
                rge_dict,
                scale=161.0 if _obs_scale == "dynamic" else _obs_scale,
            )
        else:
            rgemat = None
            coeff_names = np.array(coefficients.names)

        self.project = np.zeros((len(oo_ww_wc_basis), len(coeff_names)))
        for i, op in enumerate(oo_ww_wc_basis):
            if op in coeff_names:
                self.project[i, np.argwhere(coeff_names == op)[0, 0]] = 1

        self.datasets = {
            "FCCee_ww_lepto_161": "invcov_FCCee_ww_leptonic_161.dat",
            "FCCee_ww_semilep_161": "invcov_FCCee_ww_semilep_161.dat",
        }

        incovs_reordered = []
        for path in self.datasets.values():
            invcov = np.loadtxt(current_file_path / path)
            temp = jnp.einsum("ij, jk, kl", self.project.T, invcov, self.project)
            incovs_reordered.append(temp)
        self.incov_tot = jnp.sum(jnp.array(incovs_reordered), axis=0)

        self.incov_tot *= lumi_scale

        self.rgemat = rgemat

        if self.rgemat is not None:
            self.incov_tot = jnp.einsum(
                "ij, jk, kl", self.rgemat.T, self.incov_tot, self.rgemat
            )

        self.coefficients = coefficients
        self.num_data = len(oo_ww_wc_basis)

    def compute_chi2(self, coefficient_values):
        resolved = self.coefficients.resolve(coefficient_values)
        return jnp.einsum("i, ij, j", resolved, self.incov_tot, resolved)


class DescopedOptimalWWFCCee240:
    def __init__(self, coefficients, rge_dict=None, lumi_scale=1.0):
        if rge_dict is not None:
            _obs_scale = rge_dict.get("obs_scale", "dynamic")
            rgemat, coeff_names = compute_rge_matrix(
                coefficients,
                rge_dict,
                scale=240.0 if _obs_scale == "dynamic" else _obs_scale,
            )
        else:
            rgemat = None
            coeff_names = np.array(coefficients.names)

        self.project = np.zeros((len(oo_ww_wc_basis), len(coeff_names)))
        for i, op in enumerate(oo_ww_wc_basis):
            if op in coeff_names:
                self.project[i, np.argwhere(coeff_names == op)[0, 0]] = 1

        self.datasets = {
            "FCCee_ww_lepto_240": "invcov_FCCee_ww_leptonic_240.dat",
            "FCCee_ww_semilep_240": "invcov_FCCee_ww_semilep_240.dat",
        }

        incovs_reordered = []
        for path in self.datasets.values():
            invcov = np.loadtxt(current_file_path / path)
            temp = jnp.einsum("ij, jk, kl", self.project.T, invcov, self.project)
            incovs_reordered.append(temp)
        self.incov_tot = jnp.sum(jnp.array(incovs_reordered), axis=0)

        self.incov_tot *= lumi_scale

        self.rgemat = rgemat

        if self.rgemat is not None:
            self.incov_tot = jnp.einsum(
                "ij, jk, kl", self.rgemat.T, self.incov_tot, self.rgemat
            )

        self.coefficients = coefficients
        self.num_data = len(oo_ww_wc_basis)

    def compute_chi2(self, coefficient_values):
        resolved = self.coefficients.resolve(coefficient_values)
        return jnp.einsum("i, ij, j", resolved, self.incov_tot, resolved)
